"""Build static/sample_pool.js: the curated pool behind the UI's "Shuffle" button.

Read-only over the frozen gold set and the jury scores; run manually when the
pool needs regenerating (the output is committed, nothing runs at request time).

Pool rule (2026-09):
  * exclude the 6 items the jury scored wrong for GraphRAG (derived from
    aggregated_jury_scores.json, not hard-coded);
  * exclude the 5 "accepted miss" items documented in the router header
    (FH03, MH01, CD03, AF01, AF04);
  * 34 items remain; trim to 30 by dropping split-vote items (majority
    correct, one judge dissenting) from the largest categories: OS04, OS06,
    MH04, CD07. DA03 (also split-vote) stays because DA is the smallest of
    the affected categories.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
GOLD = ROOT / "evaluation/gold_set/aeroops_goldset_v1_frozen.json"
JURY = ROOT / "evaluation/jury_scoring/aggregated_jury_scores.json"
OUT = ROOT / "static/sample_pool.js"

ACCEPTED_MISSES = {"FH03", "MH01", "CD03", "AF01", "AF04"}
TRIMMED_SPLIT_VOTES = {"OS04", "OS06", "MH04", "CD07"}
POOL_SIZE = 30

LABELS = {
    "factual_single_hop": "Factual",
    "multi_hop_causal": "Multi-hop causal",
    "cross_document": "Cross-document",
    "aggregation_fanout": "Aggregation",
    "disambiguation": "Disambiguation",
    "operational_scenario": "Operational scenario",
    "provenance": "Provenance",
}


def build():
    gold = json.loads(GOLD.read_text(encoding="utf-8"))
    jury = {x["id"]: x for x in json.loads(JURY.read_text(encoding="utf-8"))["per_item"]}
    wrong = {i for i, x in jury.items() if not x["graphrag"]["correct"]}
    excluded = wrong | ACCEPTED_MISSES | TRIMMED_SPLIT_VOTES
    pool = [g for g in gold if g["id"] not in excluded]
    assert len(pool) == POOL_SIZE, len(pool)
    return wrong, [
        {"id": g["id"], "category": g["category"], "label": LABELS[g["category"]], "question": g["question"]}
        for g in pool
    ]


if __name__ == "__main__":
    wrong, pool = build()
    body = json.dumps(pool, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by build_sample_pool.py -- do not edit by hand.\n"
        "// Curated from jury-correct gold-set questions; see that script for the rule.\n"
        f"window.AEROOPS_SAMPLE_POOL = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(pool)} questions); jury-wrong excluded: {sorted(wrong)}")
